language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-generator-responsive' ]; then cd .. && eval "mv $currentfolder generator-generator-responsive" && cd generator-generator-responsive; fi

